### ISSUE TITLE
make icons clickable

### ISSUE THREAD

**Issue by serpilb** [SNAS/website#32]
@Matvey-Kuk can you figure out if we can just click on the icons to see the content instead of needing to click on the button below? We can leave the buttons as well but it'd be really nice if the icons were clickable as well.

**Comment by TimEvens** [comment]
@manbhard  is going to look at this.

**Comment by manbhard** [comment]
Regarding this issue, @TimEvens and I discussed it and the buttons do look nice for now. I have removed the "Read more->" link in many of the tiles since the entire tile is a link.
