### ISSUE TITLE
Modify footer.html for snas

### ISSUE THREAD

**Issue by serpilb** [SNAS/website#6]
Align "SNAS, Home, About, Contact" horizontally.  Anything else we should add here?

**Comment by Matvey-Kuk** [comment]
@serpilb ready

**Comment by serpilb** [comment]
@Matvey-Kuk Can you organize the footer to look like this:

http://www.nominum.com/

**Comment by TimEvens** [comment]
@manbhard  is going to look at this.

**Comment by TimEvens** [comment]
Fixed with PR #55
